In [2]:
import numpy as np

In [18]:
notre_tableau = np.array([x for x in range(1, 20)])

In [19]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
tableau_2_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
tableau_2_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
sous_tableau = notre_tableau[0:5]

In [22]:
sous_tableau

array([1, 2, 3, 4, 5])

In [27]:
new_table = np.array([[x for x in range(0, 10)], [x for x in range(10, 20)], [x for x in range(20, 30)]])

In [28]:
new_table


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
new_table[1, 1]

11

In [31]:
lst = [[x for x in range(0, 10)], [x for x in range(10, 20)], [x for x in range(20, 30)]]

In [33]:
lst

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [35]:
lst[1][4]

14

In [36]:
lst[1, 4]

TypeError: list indices must be integers or slices, not tuple

In [39]:
lst[2][:]

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [44]:
lst

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [51]:
lst[:][-1]

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [54]:
new_table.size

30

In [56]:
new_table.size

30

In [4]:
houses = np.genfromtxt("Houses.csv", delimiter=",", dtype=int)

In [5]:
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [7]:
houses[:, 0]=houses[:, 0]*0.86

In [8]:
houses

array([[182320,   4148,  25264],
       [197800,   2501,  11891],
       [291540,   4374,  25351],
       [248540,   2398,  22215],
       [137600,   2536,   9234],
       [ 73100,   2368,  13329],
       [ 73100,   1264,   8407],
       [124700,   1572,  12588],
       [141040,   2375,  16204],
       [106210,   1161,   9626],
       [154800,   1542,   8755],
       [137170,   1464,  14636],
       [134160,   2240,  21780],
       [125990,   1269,  11250],
       [ 87290,    924,   7361],
       [ 94428,    768,  10497],
       [156520,   1320,  15768],
       [ 94600,   1845,  12153],
       [107500,   1274,  13634],
       [ 68800,   1905,  10890]])

In [9]:
houses[:,1]=houses[:,1]*0.09

In [10]:
houses

array([[182320,    373,  25264],
       [197800,    225,  11891],
       [291540,    393,  25351],
       [248540,    215,  22215],
       [137600,    228,   9234],
       [ 73100,    213,  13329],
       [ 73100,    113,   8407],
       [124700,    141,  12588],
       [141040,    213,  16204],
       [106210,    104,   9626],
       [154800,    138,   8755],
       [137170,    131,  14636],
       [134160,    201,  21780],
       [125990,    114,  11250],
       [ 87290,     83,   7361],
       [ 94428,     69,  10497],
       [156520,    118,  15768],
       [ 94600,    166,  12153],
       [107500,    114,  13634],
       [ 68800,    171,  10890]])

In [11]:
houses[:,2]=houses[:,2]*0.09

In [12]:
houses

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])

In [13]:
houses[houses[:,2]>1000]

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [ 73100,    213,   1199],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227]])

In [14]:
len(houses[houses[:,2]>1000])

13

In [15]:
np.sum(houses[:,0])

2737208

In [16]:
prix_max=np.max(houses[:,0])
print(prix_max)

291540


In [19]:
print(houses[houses[:,0]==np.max(houses[:,0])][:,1])

[393]


In [20]:
prix, taille_maison, taiale_terrain = np.hsplit(houses, 3)

In [21]:
prix

array([[182320],
       [197800],
       [291540],
       [248540],
       [137600],
       [ 73100],
       [ 73100],
       [124700],
       [141040],
       [106210],
       [154800],
       [137170],
       [134160],
       [125990],
       [ 87290],
       [ 94428],
       [156520],
       [ 94600],
       [107500],
       [ 68800]])

In [22]:
taille_maison

array([[373],
       [225],
       [393],
       [215],
       [228],
       [213],
       [113],
       [141],
       [213],
       [104],
       [138],
       [131],
       [201],
       [114],
       [ 83],
       [ 69],
       [118],
       [166],
       [114],
       [171]])

In [24]:
np.concatenate([prix, taille_maison, taiale_terrain], axis=1)

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])